/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConnectorMetadataSalesforce
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ConnectorMetadataSalesforce {
  public static final String SERIALIZED_NAME_O_AUTH_SCOPES = "oAuthScopes";
  @SerializedName(SERIALIZED_NAME_O_AUTH_SCOPES)
  @javax.annotation.Nullable
  private List oAuthScopes;

  public static final String SERIALIZED_NAME_DATA_TRANSFER_APIS = "dataTransferApis";
  @SerializedName(SERIALIZED_NAME_DATA_TRANSFER_APIS)
  @javax.annotation.Nullable
  private List dataTransferApis;

  public static final String SERIALIZED_NAME_OAUTH2_GRANT_TYPES_SUPPORTED = "oauth2GrantTypesSupported";
  @SerializedName(SERIALIZED_NAME_OAUTH2_GRANT_TYPES_SUPPORTED)
  @javax.annotation.Nullable
  private List oauth2GrantTypesSupported;

  public ConnectorMetadataSalesforce() {
  }

  public ConnectorMetadataSalesforce oAuthScopes(@javax.annotation.Nullable List oAuthScopes) {
    this.oAuthScopes = oAuthScopes;
    return this;
  }

  /**
   * Get oAuthScopes
   * @return oAuthScopes
   */
  @javax.annotation.Nullable
  public List getoAuthScopes() {
    return oAuthScopes;
  }

  public void setoAuthScopes(@javax.annotation.Nullable List oAuthScopes) {
    this.oAuthScopes = oAuthScopes;
  }


  public ConnectorMetadataSalesforce dataTransferApis(@javax.annotation.Nullable List dataTransferApis) {
    this.dataTransferApis = dataTransferApis;
    return this;
  }

  /**
   * Get dataTransferApis
   * @return dataTransferApis
   */
  @javax.annotation.Nullable
  public List getDataTransferApis() {
    return dataTransferApis;
  }

  public void setDataTransferApis(@javax.annotation.Nullable List dataTransferApis) {
    this.dataTransferApis = dataTransferApis;
  }


  public ConnectorMetadataSalesforce oauth2GrantTypesSupported(@javax.annotation.Nullable List oauth2GrantTypesSupported) {
    this.oauth2GrantTypesSupported = oauth2GrantTypesSupported;
    return this;
  }

  /**
   * Get oauth2GrantTypesSupported
   * @return oauth2GrantTypesSupported
   */
  @javax.annotation.Nullable
  public List getOauth2GrantTypesSupported() {
    return oauth2GrantTypesSupported;
  }

  public void setOauth2GrantTypesSupported(@javax.annotation.Nullable List oauth2GrantTypesSupported) {
    this.oauth2GrantTypesSupported = oauth2GrantTypesSupported;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorMetadataSalesforce connectorMetadataSalesforce = (ConnectorMetadataSalesforce) o;
    return Objects.equals(this.oAuthScopes, connectorMetadataSalesforce.oAuthScopes) &&
        Objects.equals(this.dataTransferApis, connectorMetadataSalesforce.dataTransferApis) &&
        Objects.equals(this.oauth2GrantTypesSupported, connectorMetadataSalesforce.oauth2GrantTypesSupported);
  }

  @Override
  public int hashCode() {
    return Objects.hash(oAuthScopes, dataTransferApis, oauth2GrantTypesSupported);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorMetadataSalesforce {\n");
    sb.append("    oAuthScopes: ").append(toIndentedString(oAuthScopes)).append("\n");
    sb.append("    dataTransferApis: ").append(toIndentedString(dataTransferApis)).append("\n");
    sb.append("    oauth2GrantTypesSupported: ").append(toIndentedString(oauth2GrantTypesSupported)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("oAuthScopes");
    openapiFields.add("dataTransferApis");
    openapiFields.add("oauth2GrantTypesSupported");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConnectorMetadataSalesforce
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConnectorMetadataSalesforce.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConnectorMetadataSalesforce is not found in the empty JSON string", ConnectorMetadataSalesforce.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConnectorMetadataSalesforce.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConnectorMetadataSalesforce` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `oAuthScopes`
      if (jsonObj.get("oAuthScopes") != null && !jsonObj.get("oAuthScopes").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("oAuthScopes"));
      }
      // validate the optional field `dataTransferApis`
      if (jsonObj.get("dataTransferApis") != null && !jsonObj.get("dataTransferApis").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("dataTransferApis"));
      }
      // validate the optional field `oauth2GrantTypesSupported`
      if (jsonObj.get("oauth2GrantTypesSupported") != null && !jsonObj.get("oauth2GrantTypesSupported").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("oauth2GrantTypesSupported"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectorMetadataSalesforce.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectorMetadataSalesforce' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectorMetadataSalesforce> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectorMetadataSalesforce.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectorMetadataSalesforce>() {
           @Override
           public void write(JsonWriter out, ConnectorMetadataSalesforce value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectorMetadataSalesforce read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConnectorMetadataSalesforce given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConnectorMetadataSalesforce
   * @throws IOException if the JSON string is invalid with respect to ConnectorMetadataSalesforce
   */
  public static ConnectorMetadataSalesforce fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectorMetadataSalesforce.class);
  }

  /**
   * Convert an instance of ConnectorMetadataSalesforce to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

