/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConnectorProfileCredentialsInforNexus
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ConnectorProfileCredentialsInforNexus {
  public static final String SERIALIZED_NAME_ACCESS_KEY_ID = "accessKeyId";
  @SerializedName(SERIALIZED_NAME_ACCESS_KEY_ID)
  @javax.annotation.Nonnull
  private String accessKeyId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  @javax.annotation.Nonnull
  private String userId;

  public static final String SERIALIZED_NAME_SECRET_ACCESS_KEY = "secretAccessKey";
  @SerializedName(SERIALIZED_NAME_SECRET_ACCESS_KEY)
  @javax.annotation.Nonnull
  private String secretAccessKey;

  public static final String SERIALIZED_NAME_DATAKEY = "datakey";
  @SerializedName(SERIALIZED_NAME_DATAKEY)
  @javax.annotation.Nonnull
  private String datakey;

  public ConnectorProfileCredentialsInforNexus() {
  }

  public ConnectorProfileCredentialsInforNexus accessKeyId(@javax.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
    return this;
  }

  /**
   * Get accessKeyId
   * @return accessKeyId
   */
  @javax.annotation.Nonnull
  public String getAccessKeyId() {
    return accessKeyId;
  }

  public void setAccessKeyId(@javax.annotation.Nonnull String accessKeyId) {
    this.accessKeyId = accessKeyId;
  }


  public ConnectorProfileCredentialsInforNexus userId(@javax.annotation.Nonnull String userId) {
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @javax.annotation.Nonnull
  public String getUserId() {
    return userId;
  }

  public void setUserId(@javax.annotation.Nonnull String userId) {
    this.userId = userId;
  }


  public ConnectorProfileCredentialsInforNexus secretAccessKey(@javax.annotation.Nonnull String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
    return this;
  }

  /**
   * Get secretAccessKey
   * @return secretAccessKey
   */
  @javax.annotation.Nonnull
  public String getSecretAccessKey() {
    return secretAccessKey;
  }

  public void setSecretAccessKey(@javax.annotation.Nonnull String secretAccessKey) {
    this.secretAccessKey = secretAccessKey;
  }


  public ConnectorProfileCredentialsInforNexus datakey(@javax.annotation.Nonnull String datakey) {
    this.datakey = datakey;
    return this;
  }

  /**
   * Get datakey
   * @return datakey
   */
  @javax.annotation.Nonnull
  public String getDatakey() {
    return datakey;
  }

  public void setDatakey(@javax.annotation.Nonnull String datakey) {
    this.datakey = datakey;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorProfileCredentialsInforNexus connectorProfileCredentialsInforNexus = (ConnectorProfileCredentialsInforNexus) o;
    return Objects.equals(this.accessKeyId, connectorProfileCredentialsInforNexus.accessKeyId) &&
        Objects.equals(this.userId, connectorProfileCredentialsInforNexus.userId) &&
        Objects.equals(this.secretAccessKey, connectorProfileCredentialsInforNexus.secretAccessKey) &&
        Objects.equals(this.datakey, connectorProfileCredentialsInforNexus.datakey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accessKeyId, userId, secretAccessKey, datakey);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorProfileCredentialsInforNexus {\n");
    sb.append("    accessKeyId: ").append(toIndentedString(accessKeyId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    secretAccessKey: ").append(toIndentedString(secretAccessKey)).append("\n");
    sb.append("    datakey: ").append(toIndentedString(datakey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("accessKeyId");
    openapiFields.add("userId");
    openapiFields.add("secretAccessKey");
    openapiFields.add("datakey");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("accessKeyId");
    openapiRequiredFields.add("userId");
    openapiRequiredFields.add("secretAccessKey");
    openapiRequiredFields.add("datakey");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConnectorProfileCredentialsInforNexus
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConnectorProfileCredentialsInforNexus.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConnectorProfileCredentialsInforNexus is not found in the empty JSON string", ConnectorProfileCredentialsInforNexus.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConnectorProfileCredentialsInforNexus.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConnectorProfileCredentialsInforNexus` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConnectorProfileCredentialsInforNexus.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `accessKeyId`
      String.validateJsonElement(jsonObj.get("accessKeyId"));
      // validate the required field `userId`
      String.validateJsonElement(jsonObj.get("userId"));
      // validate the required field `secretAccessKey`
      String.validateJsonElement(jsonObj.get("secretAccessKey"));
      // validate the required field `datakey`
      String.validateJsonElement(jsonObj.get("datakey"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectorProfileCredentialsInforNexus.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectorProfileCredentialsInforNexus' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectorProfileCredentialsInforNexus> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectorProfileCredentialsInforNexus.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectorProfileCredentialsInforNexus>() {
           @Override
           public void write(JsonWriter out, ConnectorProfileCredentialsInforNexus value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectorProfileCredentialsInforNexus read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConnectorProfileCredentialsInforNexus given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConnectorProfileCredentialsInforNexus
   * @throws IOException if the JSON string is invalid with respect to ConnectorProfileCredentialsInforNexus
   */
  public static ConnectorProfileCredentialsInforNexus fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectorProfileCredentialsInforNexus.class);
  }

  /**
   * Convert an instance of ConnectorProfileCredentialsInforNexus to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

