/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ConnectorEntityFieldSourceProperties
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ConnectorEntityFieldSourceProperties {
  public static final String SERIALIZED_NAME_IS_RETRIEVABLE = "isRetrievable";
  @SerializedName(SERIALIZED_NAME_IS_RETRIEVABLE)
  @javax.annotation.Nullable
  private Boolean isRetrievable;

  public static final String SERIALIZED_NAME_IS_QUERYABLE = "isQueryable";
  @SerializedName(SERIALIZED_NAME_IS_QUERYABLE)
  @javax.annotation.Nullable
  private Boolean isQueryable;

  public static final String SERIALIZED_NAME_IS_TIMESTAMP_FIELD_FOR_INCREMENTAL_QUERIES = "isTimestampFieldForIncrementalQueries";
  @SerializedName(SERIALIZED_NAME_IS_TIMESTAMP_FIELD_FOR_INCREMENTAL_QUERIES)
  @javax.annotation.Nullable
  private Boolean isTimestampFieldForIncrementalQueries;

  public ConnectorEntityFieldSourceProperties() {
  }

  public ConnectorEntityFieldSourceProperties isRetrievable(@javax.annotation.Nullable Boolean isRetrievable) {
    this.isRetrievable = isRetrievable;
    return this;
  }

  /**
   * Get isRetrievable
   * @return isRetrievable
   */
  @javax.annotation.Nullable
  public Boolean getIsRetrievable() {
    return isRetrievable;
  }

  public void setIsRetrievable(@javax.annotation.Nullable Boolean isRetrievable) {
    this.isRetrievable = isRetrievable;
  }


  public ConnectorEntityFieldSourceProperties isQueryable(@javax.annotation.Nullable Boolean isQueryable) {
    this.isQueryable = isQueryable;
    return this;
  }

  /**
   * Get isQueryable
   * @return isQueryable
   */
  @javax.annotation.Nullable
  public Boolean getIsQueryable() {
    return isQueryable;
  }

  public void setIsQueryable(@javax.annotation.Nullable Boolean isQueryable) {
    this.isQueryable = isQueryable;
  }


  public ConnectorEntityFieldSourceProperties isTimestampFieldForIncrementalQueries(@javax.annotation.Nullable Boolean isTimestampFieldForIncrementalQueries) {
    this.isTimestampFieldForIncrementalQueries = isTimestampFieldForIncrementalQueries;
    return this;
  }

  /**
   * Get isTimestampFieldForIncrementalQueries
   * @return isTimestampFieldForIncrementalQueries
   */
  @javax.annotation.Nullable
  public Boolean getIsTimestampFieldForIncrementalQueries() {
    return isTimestampFieldForIncrementalQueries;
  }

  public void setIsTimestampFieldForIncrementalQueries(@javax.annotation.Nullable Boolean isTimestampFieldForIncrementalQueries) {
    this.isTimestampFieldForIncrementalQueries = isTimestampFieldForIncrementalQueries;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConnectorEntityFieldSourceProperties connectorEntityFieldSourceProperties = (ConnectorEntityFieldSourceProperties) o;
    return Objects.equals(this.isRetrievable, connectorEntityFieldSourceProperties.isRetrievable) &&
        Objects.equals(this.isQueryable, connectorEntityFieldSourceProperties.isQueryable) &&
        Objects.equals(this.isTimestampFieldForIncrementalQueries, connectorEntityFieldSourceProperties.isTimestampFieldForIncrementalQueries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isRetrievable, isQueryable, isTimestampFieldForIncrementalQueries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConnectorEntityFieldSourceProperties {\n");
    sb.append("    isRetrievable: ").append(toIndentedString(isRetrievable)).append("\n");
    sb.append("    isQueryable: ").append(toIndentedString(isQueryable)).append("\n");
    sb.append("    isTimestampFieldForIncrementalQueries: ").append(toIndentedString(isTimestampFieldForIncrementalQueries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("isRetrievable");
    openapiFields.add("isQueryable");
    openapiFields.add("isTimestampFieldForIncrementalQueries");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ConnectorEntityFieldSourceProperties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ConnectorEntityFieldSourceProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConnectorEntityFieldSourceProperties is not found in the empty JSON string", ConnectorEntityFieldSourceProperties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ConnectorEntityFieldSourceProperties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConnectorEntityFieldSourceProperties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `isRetrievable`
      if (jsonObj.get("isRetrievable") != null && !jsonObj.get("isRetrievable").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isRetrievable"));
      }
      // validate the optional field `isQueryable`
      if (jsonObj.get("isQueryable") != null && !jsonObj.get("isQueryable").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isQueryable"));
      }
      // validate the optional field `isTimestampFieldForIncrementalQueries`
      if (jsonObj.get("isTimestampFieldForIncrementalQueries") != null && !jsonObj.get("isTimestampFieldForIncrementalQueries").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isTimestampFieldForIncrementalQueries"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConnectorEntityFieldSourceProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConnectorEntityFieldSourceProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConnectorEntityFieldSourceProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConnectorEntityFieldSourceProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<ConnectorEntityFieldSourceProperties>() {
           @Override
           public void write(JsonWriter out, ConnectorEntityFieldSourceProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConnectorEntityFieldSourceProperties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ConnectorEntityFieldSourceProperties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ConnectorEntityFieldSourceProperties
   * @throws IOException if the JSON string is invalid with respect to ConnectorEntityFieldSourceProperties
   */
  public static ConnectorEntityFieldSourceProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConnectorEntityFieldSourceProperties.class);
  }

  /**
   * Convert an instance of ConnectorEntityFieldSourceProperties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

