/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.AuthenticationType;
import org.openapitools.client.model.CustomConnectorProfileCredentialsApiKey;
import org.openapitools.client.model.CustomConnectorProfileCredentialsBasic;
import org.openapitools.client.model.CustomConnectorProfileCredentialsCustom;
import org.openapitools.client.model.CustomConnectorProfileCredentialsOauth2;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The connector-specific profile credentials that are required when using the custom connector.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CustomConnectorProfileCredentials {
  public static final String SERIALIZED_NAME_AUTHENTICATION_TYPE = "authenticationType";
  @SerializedName(SERIALIZED_NAME_AUTHENTICATION_TYPE)
  @javax.annotation.Nonnull
  private AuthenticationType authenticationType;

  public static final String SERIALIZED_NAME_BASIC = "basic";
  @SerializedName(SERIALIZED_NAME_BASIC)
  @javax.annotation.Nullable
  private CustomConnectorProfileCredentialsBasic basic;

  public static final String SERIALIZED_NAME_OAUTH2 = "oauth2";
  @SerializedName(SERIALIZED_NAME_OAUTH2)
  @javax.annotation.Nullable
  private CustomConnectorProfileCredentialsOauth2 oauth2;

  public static final String SERIALIZED_NAME_API_KEY = "apiKey";
  @SerializedName(SERIALIZED_NAME_API_KEY)
  @javax.annotation.Nullable
  private CustomConnectorProfileCredentialsApiKey apiKey;

  public static final String SERIALIZED_NAME_CUSTOM = "custom";
  @SerializedName(SERIALIZED_NAME_CUSTOM)
  @javax.annotation.Nullable
  private CustomConnectorProfileCredentialsCustom custom;

  public CustomConnectorProfileCredentials() {
  }

  public CustomConnectorProfileCredentials authenticationType(@javax.annotation.Nonnull AuthenticationType authenticationType) {
    this.authenticationType = authenticationType;
    return this;
  }

  /**
   * Get authenticationType
   * @return authenticationType
   */
  @javax.annotation.Nonnull
  public AuthenticationType getAuthenticationType() {
    return authenticationType;
  }

  public void setAuthenticationType(@javax.annotation.Nonnull AuthenticationType authenticationType) {
    this.authenticationType = authenticationType;
  }


  public CustomConnectorProfileCredentials basic(@javax.annotation.Nullable CustomConnectorProfileCredentialsBasic basic) {
    this.basic = basic;
    return this;
  }

  /**
   * Get basic
   * @return basic
   */
  @javax.annotation.Nullable
  public CustomConnectorProfileCredentialsBasic getBasic() {
    return basic;
  }

  public void setBasic(@javax.annotation.Nullable CustomConnectorProfileCredentialsBasic basic) {
    this.basic = basic;
  }


  public CustomConnectorProfileCredentials oauth2(@javax.annotation.Nullable CustomConnectorProfileCredentialsOauth2 oauth2) {
    this.oauth2 = oauth2;
    return this;
  }

  /**
   * Get oauth2
   * @return oauth2
   */
  @javax.annotation.Nullable
  public CustomConnectorProfileCredentialsOauth2 getOauth2() {
    return oauth2;
  }

  public void setOauth2(@javax.annotation.Nullable CustomConnectorProfileCredentialsOauth2 oauth2) {
    this.oauth2 = oauth2;
  }


  public CustomConnectorProfileCredentials apiKey(@javax.annotation.Nullable CustomConnectorProfileCredentialsApiKey apiKey) {
    this.apiKey = apiKey;
    return this;
  }

  /**
   * Get apiKey
   * @return apiKey
   */
  @javax.annotation.Nullable
  public CustomConnectorProfileCredentialsApiKey getApiKey() {
    return apiKey;
  }

  public void setApiKey(@javax.annotation.Nullable CustomConnectorProfileCredentialsApiKey apiKey) {
    this.apiKey = apiKey;
  }


  public CustomConnectorProfileCredentials custom(@javax.annotation.Nullable CustomConnectorProfileCredentialsCustom custom) {
    this.custom = custom;
    return this;
  }

  /**
   * Get custom
   * @return custom
   */
  @javax.annotation.Nullable
  public CustomConnectorProfileCredentialsCustom getCustom() {
    return custom;
  }

  public void setCustom(@javax.annotation.Nullable CustomConnectorProfileCredentialsCustom custom) {
    this.custom = custom;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomConnectorProfileCredentials customConnectorProfileCredentials = (CustomConnectorProfileCredentials) o;
    return Objects.equals(this.authenticationType, customConnectorProfileCredentials.authenticationType) &&
        Objects.equals(this.basic, customConnectorProfileCredentials.basic) &&
        Objects.equals(this.oauth2, customConnectorProfileCredentials.oauth2) &&
        Objects.equals(this.apiKey, customConnectorProfileCredentials.apiKey) &&
        Objects.equals(this.custom, customConnectorProfileCredentials.custom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(authenticationType, basic, oauth2, apiKey, custom);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomConnectorProfileCredentials {\n");
    sb.append("    authenticationType: ").append(toIndentedString(authenticationType)).append("\n");
    sb.append("    basic: ").append(toIndentedString(basic)).append("\n");
    sb.append("    oauth2: ").append(toIndentedString(oauth2)).append("\n");
    sb.append("    apiKey: ").append(toIndentedString(apiKey)).append("\n");
    sb.append("    custom: ").append(toIndentedString(custom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("authenticationType");
    openapiFields.add("basic");
    openapiFields.add("oauth2");
    openapiFields.add("apiKey");
    openapiFields.add("custom");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("authenticationType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomConnectorProfileCredentials
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomConnectorProfileCredentials.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomConnectorProfileCredentials is not found in the empty JSON string", CustomConnectorProfileCredentials.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomConnectorProfileCredentials.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomConnectorProfileCredentials` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomConnectorProfileCredentials.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `authenticationType`
      AuthenticationType.validateJsonElement(jsonObj.get("authenticationType"));
      // validate the optional field `basic`
      if (jsonObj.get("basic") != null && !jsonObj.get("basic").isJsonNull()) {
        CustomConnectorProfileCredentialsBasic.validateJsonElement(jsonObj.get("basic"));
      }
      // validate the optional field `oauth2`
      if (jsonObj.get("oauth2") != null && !jsonObj.get("oauth2").isJsonNull()) {
        CustomConnectorProfileCredentialsOauth2.validateJsonElement(jsonObj.get("oauth2"));
      }
      // validate the optional field `apiKey`
      if (jsonObj.get("apiKey") != null && !jsonObj.get("apiKey").isJsonNull()) {
        CustomConnectorProfileCredentialsApiKey.validateJsonElement(jsonObj.get("apiKey"));
      }
      // validate the optional field `custom`
      if (jsonObj.get("custom") != null && !jsonObj.get("custom").isJsonNull()) {
        CustomConnectorProfileCredentialsCustom.validateJsonElement(jsonObj.get("custom"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomConnectorProfileCredentials.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomConnectorProfileCredentials' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomConnectorProfileCredentials> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomConnectorProfileCredentials.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomConnectorProfileCredentials>() {
           @Override
           public void write(JsonWriter out, CustomConnectorProfileCredentials value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomConnectorProfileCredentials read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomConnectorProfileCredentials given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomConnectorProfileCredentials
   * @throws IOException if the JSON string is invalid with respect to CustomConnectorProfileCredentials
   */
  public static CustomConnectorProfileCredentials fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomConnectorProfileCredentials.class);
  }

  /**
   * Convert an instance of CustomConnectorProfileCredentials to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

