/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import org.openapitools.client.model.CustomConnectorDestinationPropertiesErrorHandlingConfig;
import org.openapitools.client.model.WriteOperationType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The properties that are applied when the custom connector is being used as a destination.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class CustomConnectorDestinationProperties {
  public static final String SERIALIZED_NAME_ENTITY_NAME = "entityName";
  @SerializedName(SERIALIZED_NAME_ENTITY_NAME)
  @javax.annotation.Nonnull
  private String entityName;

  public static final String SERIALIZED_NAME_ERROR_HANDLING_CONFIG = "errorHandlingConfig";
  @SerializedName(SERIALIZED_NAME_ERROR_HANDLING_CONFIG)
  @javax.annotation.Nullable
  private CustomConnectorDestinationPropertiesErrorHandlingConfig errorHandlingConfig;

  public static final String SERIALIZED_NAME_WRITE_OPERATION_TYPE = "writeOperationType";
  @SerializedName(SERIALIZED_NAME_WRITE_OPERATION_TYPE)
  @javax.annotation.Nullable
  private WriteOperationType writeOperationType;

  public static final String SERIALIZED_NAME_ID_FIELD_NAMES = "idFieldNames";
  @SerializedName(SERIALIZED_NAME_ID_FIELD_NAMES)
  @javax.annotation.Nullable
  private List idFieldNames;

  public static final String SERIALIZED_NAME_CUSTOM_PROPERTIES = "customProperties";
  @SerializedName(SERIALIZED_NAME_CUSTOM_PROPERTIES)
  @javax.annotation.Nullable
  private Map customProperties;

  public CustomConnectorDestinationProperties() {
  }

  public CustomConnectorDestinationProperties entityName(@javax.annotation.Nonnull String entityName) {
    this.entityName = entityName;
    return this;
  }

  /**
   * Get entityName
   * @return entityName
   */
  @javax.annotation.Nonnull
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(@javax.annotation.Nonnull String entityName) {
    this.entityName = entityName;
  }


  public CustomConnectorDestinationProperties errorHandlingConfig(@javax.annotation.Nullable CustomConnectorDestinationPropertiesErrorHandlingConfig errorHandlingConfig) {
    this.errorHandlingConfig = errorHandlingConfig;
    return this;
  }

  /**
   * Get errorHandlingConfig
   * @return errorHandlingConfig
   */
  @javax.annotation.Nullable
  public CustomConnectorDestinationPropertiesErrorHandlingConfig getErrorHandlingConfig() {
    return errorHandlingConfig;
  }

  public void setErrorHandlingConfig(@javax.annotation.Nullable CustomConnectorDestinationPropertiesErrorHandlingConfig errorHandlingConfig) {
    this.errorHandlingConfig = errorHandlingConfig;
  }


  public CustomConnectorDestinationProperties writeOperationType(@javax.annotation.Nullable WriteOperationType writeOperationType) {
    this.writeOperationType = writeOperationType;
    return this;
  }

  /**
   * Get writeOperationType
   * @return writeOperationType
   */
  @javax.annotation.Nullable
  public WriteOperationType getWriteOperationType() {
    return writeOperationType;
  }

  public void setWriteOperationType(@javax.annotation.Nullable WriteOperationType writeOperationType) {
    this.writeOperationType = writeOperationType;
  }


  public CustomConnectorDestinationProperties idFieldNames(@javax.annotation.Nullable List idFieldNames) {
    this.idFieldNames = idFieldNames;
    return this;
  }

  /**
   * Get idFieldNames
   * @return idFieldNames
   */
  @javax.annotation.Nullable
  public List getIdFieldNames() {
    return idFieldNames;
  }

  public void setIdFieldNames(@javax.annotation.Nullable List idFieldNames) {
    this.idFieldNames = idFieldNames;
  }


  public CustomConnectorDestinationProperties customProperties(@javax.annotation.Nullable Map customProperties) {
    this.customProperties = customProperties;
    return this;
  }

  /**
   * Get customProperties
   * @return customProperties
   */
  @javax.annotation.Nullable
  public Map getCustomProperties() {
    return customProperties;
  }

  public void setCustomProperties(@javax.annotation.Nullable Map customProperties) {
    this.customProperties = customProperties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomConnectorDestinationProperties customConnectorDestinationProperties = (CustomConnectorDestinationProperties) o;
    return Objects.equals(this.entityName, customConnectorDestinationProperties.entityName) &&
        Objects.equals(this.errorHandlingConfig, customConnectorDestinationProperties.errorHandlingConfig) &&
        Objects.equals(this.writeOperationType, customConnectorDestinationProperties.writeOperationType) &&
        Objects.equals(this.idFieldNames, customConnectorDestinationProperties.idFieldNames) &&
        Objects.equals(this.customProperties, customConnectorDestinationProperties.customProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityName, errorHandlingConfig, writeOperationType, idFieldNames, customProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomConnectorDestinationProperties {\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    errorHandlingConfig: ").append(toIndentedString(errorHandlingConfig)).append("\n");
    sb.append("    writeOperationType: ").append(toIndentedString(writeOperationType)).append("\n");
    sb.append("    idFieldNames: ").append(toIndentedString(idFieldNames)).append("\n");
    sb.append("    customProperties: ").append(toIndentedString(customProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("entityName");
    openapiFields.add("errorHandlingConfig");
    openapiFields.add("writeOperationType");
    openapiFields.add("idFieldNames");
    openapiFields.add("customProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("entityName");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to CustomConnectorDestinationProperties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!CustomConnectorDestinationProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CustomConnectorDestinationProperties is not found in the empty JSON string", CustomConnectorDestinationProperties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!CustomConnectorDestinationProperties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `CustomConnectorDestinationProperties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : CustomConnectorDestinationProperties.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `entityName`
      String.validateJsonElement(jsonObj.get("entityName"));
      // validate the optional field `errorHandlingConfig`
      if (jsonObj.get("errorHandlingConfig") != null && !jsonObj.get("errorHandlingConfig").isJsonNull()) {
        CustomConnectorDestinationPropertiesErrorHandlingConfig.validateJsonElement(jsonObj.get("errorHandlingConfig"));
      }
      // validate the optional field `writeOperationType`
      if (jsonObj.get("writeOperationType") != null && !jsonObj.get("writeOperationType").isJsonNull()) {
        WriteOperationType.validateJsonElement(jsonObj.get("writeOperationType"));
      }
      // validate the optional field `idFieldNames`
      if (jsonObj.get("idFieldNames") != null && !jsonObj.get("idFieldNames").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("idFieldNames"));
      }
      // validate the optional field `customProperties`
      if (jsonObj.get("customProperties") != null && !jsonObj.get("customProperties").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("customProperties"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CustomConnectorDestinationProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CustomConnectorDestinationProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CustomConnectorDestinationProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CustomConnectorDestinationProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<CustomConnectorDestinationProperties>() {
           @Override
           public void write(JsonWriter out, CustomConnectorDestinationProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public CustomConnectorDestinationProperties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of CustomConnectorDestinationProperties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of CustomConnectorDestinationProperties
   * @throws IOException if the JSON string is invalid with respect to CustomConnectorDestinationProperties
   */
  public static CustomConnectorDestinationProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CustomConnectorDestinationProperties.class);
  }

  /**
   * Convert an instance of CustomConnectorDestinationProperties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

