/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * DescribeConnectorProfilesRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class DescribeConnectorProfilesRequest {
  public static final String SERIALIZED_NAME_CONNECTOR_PROFILE_NAMES = "connectorProfileNames";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_PROFILE_NAMES)
  @javax.annotation.Nullable
  private List<String> connectorProfileNames = new ArrayList<>();

  /**
   *  The type of connector, such as Salesforce, Amplitude, and so on. 
   */
  @JsonAdapter(ConnectorTypeEnum.Adapter.class)
  public enum ConnectorTypeEnum {
    SALESFORCE("Salesforce"),
    
    SINGULAR("Singular"),
    
    SLACK("Slack"),
    
    REDSHIFT("Redshift"),
    
    S3("S3"),
    
    MARKETO("Marketo"),
    
    GOOGLEANALYTICS("Googleanalytics"),
    
    ZENDESK("Zendesk"),
    
    SERVICENOW("Servicenow"),
    
    DATADOG("Datadog"),
    
    TRENDMICRO("Trendmicro"),
    
    SNOWFLAKE("Snowflake"),
    
    DYNATRACE("Dynatrace"),
    
    INFORNEXUS("Infornexus"),
    
    AMPLITUDE("Amplitude"),
    
    VEEVA("Veeva"),
    
    EVENT_BRIDGE("EventBridge"),
    
    LOOKOUT_METRICS("LookoutMetrics"),
    
    UPSOLVER("Upsolver"),
    
    HONEYCODE("Honeycode"),
    
    CUSTOMER_PROFILES("CustomerProfiles"),
    
    SAPO_DATA("SAPOData"),
    
    CUSTOM_CONNECTOR("CustomConnector"),
    
    PARDOT("Pardot");

    private String value;

    ConnectorTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ConnectorTypeEnum fromValue(String value) {
      for (ConnectorTypeEnum b : ConnectorTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ConnectorTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ConnectorTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ConnectorTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ConnectorTypeEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      ConnectorTypeEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_CONNECTOR_TYPE = "connectorType";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_TYPE)
  @javax.annotation.Nullable
  private ConnectorTypeEnum connectorType;

  public static final String SERIALIZED_NAME_CONNECTOR_LABEL = "connectorLabel";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_LABEL)
  @javax.annotation.Nullable
  private String connectorLabel;

  public static final String SERIALIZED_NAME_MAX_RESULTS = "maxResults";
  @SerializedName(SERIALIZED_NAME_MAX_RESULTS)
  @javax.annotation.Nullable
  private Integer maxResults;

  public static final String SERIALIZED_NAME_NEXT_TOKEN = "nextToken";
  @SerializedName(SERIALIZED_NAME_NEXT_TOKEN)
  @javax.annotation.Nullable
  private String nextToken;

  public DescribeConnectorProfilesRequest() {
  }

  public DescribeConnectorProfilesRequest connectorProfileNames(@javax.annotation.Nullable List<String> connectorProfileNames) {
    this.connectorProfileNames = connectorProfileNames;
    return this;
  }

  public DescribeConnectorProfilesRequest addConnectorProfileNamesItem(String connectorProfileNamesItem) {
    if (this.connectorProfileNames == null) {
      this.connectorProfileNames = new ArrayList<>();
    }
    this.connectorProfileNames.add(connectorProfileNamesItem);
    return this;
  }

  /**
   *  The name of the connector profile. The name is unique for each &lt;code&gt;ConnectorProfile&lt;/code&gt; in the Amazon Web Services account. 
   * @return connectorProfileNames
   */
  @javax.annotation.Nullable
  public List<String> getConnectorProfileNames() {
    return connectorProfileNames;
  }

  public void setConnectorProfileNames(@javax.annotation.Nullable List<String> connectorProfileNames) {
    this.connectorProfileNames = connectorProfileNames;
  }


  public DescribeConnectorProfilesRequest connectorType(@javax.annotation.Nullable ConnectorTypeEnum connectorType) {
    this.connectorType = connectorType;
    return this;
  }

  /**
   *  The type of connector, such as Salesforce, Amplitude, and so on. 
   * @return connectorType
   */
  @javax.annotation.Nullable
  public ConnectorTypeEnum getConnectorType() {
    return connectorType;
  }

  public void setConnectorType(@javax.annotation.Nullable ConnectorTypeEnum connectorType) {
    this.connectorType = connectorType;
  }


  public DescribeConnectorProfilesRequest connectorLabel(@javax.annotation.Nullable String connectorLabel) {
    this.connectorLabel = connectorLabel;
    return this;
  }

  /**
   * The name of the connector. The name is unique for each &lt;code&gt;ConnectorRegistration&lt;/code&gt; in your Amazon Web Services account. Only needed if calling for CUSTOMCONNECTOR connector type/.
   * @return connectorLabel
   */
  @javax.annotation.Nullable
  public String getConnectorLabel() {
    return connectorLabel;
  }

  public void setConnectorLabel(@javax.annotation.Nullable String connectorLabel) {
    this.connectorLabel = connectorLabel;
  }


  public DescribeConnectorProfilesRequest maxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
    return this;
  }

  /**
   *  Specifies the maximum number of items that should be returned in the result set. The default for &lt;code&gt;maxResults&lt;/code&gt; is 20 (for all paginated API operations). 
   * minimum: 1
   * maximum: 100
   * @return maxResults
   */
  @javax.annotation.Nullable
  public Integer getMaxResults() {
    return maxResults;
  }

  public void setMaxResults(@javax.annotation.Nullable Integer maxResults) {
    this.maxResults = maxResults;
  }


  public DescribeConnectorProfilesRequest nextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
    return this;
  }

  /**
   *  The pagination token for the next page of data. 
   * @return nextToken
   */
  @javax.annotation.Nullable
  public String getNextToken() {
    return nextToken;
  }

  public void setNextToken(@javax.annotation.Nullable String nextToken) {
    this.nextToken = nextToken;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DescribeConnectorProfilesRequest describeConnectorProfilesRequest = (DescribeConnectorProfilesRequest) o;
    return Objects.equals(this.connectorProfileNames, describeConnectorProfilesRequest.connectorProfileNames) &&
        Objects.equals(this.connectorType, describeConnectorProfilesRequest.connectorType) &&
        Objects.equals(this.connectorLabel, describeConnectorProfilesRequest.connectorLabel) &&
        Objects.equals(this.maxResults, describeConnectorProfilesRequest.maxResults) &&
        Objects.equals(this.nextToken, describeConnectorProfilesRequest.nextToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(connectorProfileNames, connectorType, connectorLabel, maxResults, nextToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DescribeConnectorProfilesRequest {\n");
    sb.append("    connectorProfileNames: ").append(toIndentedString(connectorProfileNames)).append("\n");
    sb.append("    connectorType: ").append(toIndentedString(connectorType)).append("\n");
    sb.append("    connectorLabel: ").append(toIndentedString(connectorLabel)).append("\n");
    sb.append("    maxResults: ").append(toIndentedString(maxResults)).append("\n");
    sb.append("    nextToken: ").append(toIndentedString(nextToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("connectorProfileNames");
    openapiFields.add("connectorType");
    openapiFields.add("connectorLabel");
    openapiFields.add("maxResults");
    openapiFields.add("nextToken");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to DescribeConnectorProfilesRequest
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!DescribeConnectorProfilesRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DescribeConnectorProfilesRequest is not found in the empty JSON string", DescribeConnectorProfilesRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!DescribeConnectorProfilesRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DescribeConnectorProfilesRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("connectorProfileNames") != null && !jsonObj.get("connectorProfileNames").isJsonNull() && !jsonObj.get("connectorProfileNames").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `connectorProfileNames` to be an array in the JSON string but got `%s`", jsonObj.get("connectorProfileNames").toString()));
      }
      if ((jsonObj.get("connectorType") != null && !jsonObj.get("connectorType").isJsonNull()) && !jsonObj.get("connectorType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connectorType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connectorType").toString()));
      }
      // validate the optional field `connectorType`
      if (jsonObj.get("connectorType") != null && !jsonObj.get("connectorType").isJsonNull()) {
        ConnectorTypeEnum.validateJsonElement(jsonObj.get("connectorType"));
      }
      if ((jsonObj.get("connectorLabel") != null && !jsonObj.get("connectorLabel").isJsonNull()) && !jsonObj.get("connectorLabel").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `connectorLabel` to be a primitive type in the JSON string but got `%s`", jsonObj.get("connectorLabel").toString()));
      }
      if ((jsonObj.get("nextToken") != null && !jsonObj.get("nextToken").isJsonNull()) && !jsonObj.get("nextToken").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `nextToken` to be a primitive type in the JSON string but got `%s`", jsonObj.get("nextToken").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DescribeConnectorProfilesRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DescribeConnectorProfilesRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DescribeConnectorProfilesRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DescribeConnectorProfilesRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<DescribeConnectorProfilesRequest>() {
           @Override
           public void write(JsonWriter out, DescribeConnectorProfilesRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DescribeConnectorProfilesRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of DescribeConnectorProfilesRequest given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of DescribeConnectorProfilesRequest
   * @throws IOException if the JSON string is invalid with respect to DescribeConnectorProfilesRequest
   */
  public static DescribeConnectorProfilesRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DescribeConnectorProfilesRequest.class);
  }

  /**
   * Convert an instance of DescribeConnectorProfilesRequest to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

