/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.ExecutionResultErrorInfo;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 *  Specifies the end result of the flow run. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class ExecutionResult {
  public static final String SERIALIZED_NAME_ERROR_INFO = "errorInfo";
  @SerializedName(SERIALIZED_NAME_ERROR_INFO)
  @javax.annotation.Nullable
  private ExecutionResultErrorInfo errorInfo;

  public static final String SERIALIZED_NAME_BYTES_PROCESSED = "bytesProcessed";
  @SerializedName(SERIALIZED_NAME_BYTES_PROCESSED)
  @javax.annotation.Nullable
  private Integer bytesProcessed;

  public static final String SERIALIZED_NAME_BYTES_WRITTEN = "bytesWritten";
  @SerializedName(SERIALIZED_NAME_BYTES_WRITTEN)
  @javax.annotation.Nullable
  private Integer bytesWritten;

  public static final String SERIALIZED_NAME_RECORDS_PROCESSED = "recordsProcessed";
  @SerializedName(SERIALIZED_NAME_RECORDS_PROCESSED)
  @javax.annotation.Nullable
  private Integer recordsProcessed;

  public ExecutionResult() {
  }

  public ExecutionResult errorInfo(@javax.annotation.Nullable ExecutionResultErrorInfo errorInfo) {
    this.errorInfo = errorInfo;
    return this;
  }

  /**
   * Get errorInfo
   * @return errorInfo
   */
  @javax.annotation.Nullable
  public ExecutionResultErrorInfo getErrorInfo() {
    return errorInfo;
  }

  public void setErrorInfo(@javax.annotation.Nullable ExecutionResultErrorInfo errorInfo) {
    this.errorInfo = errorInfo;
  }


  public ExecutionResult bytesProcessed(@javax.annotation.Nullable Integer bytesProcessed) {
    this.bytesProcessed = bytesProcessed;
    return this;
  }

  /**
   * Get bytesProcessed
   * @return bytesProcessed
   */
  @javax.annotation.Nullable
  public Integer getBytesProcessed() {
    return bytesProcessed;
  }

  public void setBytesProcessed(@javax.annotation.Nullable Integer bytesProcessed) {
    this.bytesProcessed = bytesProcessed;
  }


  public ExecutionResult bytesWritten(@javax.annotation.Nullable Integer bytesWritten) {
    this.bytesWritten = bytesWritten;
    return this;
  }

  /**
   * Get bytesWritten
   * @return bytesWritten
   */
  @javax.annotation.Nullable
  public Integer getBytesWritten() {
    return bytesWritten;
  }

  public void setBytesWritten(@javax.annotation.Nullable Integer bytesWritten) {
    this.bytesWritten = bytesWritten;
  }


  public ExecutionResult recordsProcessed(@javax.annotation.Nullable Integer recordsProcessed) {
    this.recordsProcessed = recordsProcessed;
    return this;
  }

  /**
   * Get recordsProcessed
   * @return recordsProcessed
   */
  @javax.annotation.Nullable
  public Integer getRecordsProcessed() {
    return recordsProcessed;
  }

  public void setRecordsProcessed(@javax.annotation.Nullable Integer recordsProcessed) {
    this.recordsProcessed = recordsProcessed;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExecutionResult executionResult = (ExecutionResult) o;
    return Objects.equals(this.errorInfo, executionResult.errorInfo) &&
        Objects.equals(this.bytesProcessed, executionResult.bytesProcessed) &&
        Objects.equals(this.bytesWritten, executionResult.bytesWritten) &&
        Objects.equals(this.recordsProcessed, executionResult.recordsProcessed);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorInfo, bytesProcessed, bytesWritten, recordsProcessed);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExecutionResult {\n");
    sb.append("    errorInfo: ").append(toIndentedString(errorInfo)).append("\n");
    sb.append("    bytesProcessed: ").append(toIndentedString(bytesProcessed)).append("\n");
    sb.append("    bytesWritten: ").append(toIndentedString(bytesWritten)).append("\n");
    sb.append("    recordsProcessed: ").append(toIndentedString(recordsProcessed)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("errorInfo");
    openapiFields.add("bytesProcessed");
    openapiFields.add("bytesWritten");
    openapiFields.add("recordsProcessed");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ExecutionResult
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ExecutionResult.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ExecutionResult is not found in the empty JSON string", ExecutionResult.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ExecutionResult.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ExecutionResult` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `errorInfo`
      if (jsonObj.get("errorInfo") != null && !jsonObj.get("errorInfo").isJsonNull()) {
        ExecutionResultErrorInfo.validateJsonElement(jsonObj.get("errorInfo"));
      }
      // validate the optional field `bytesProcessed`
      if (jsonObj.get("bytesProcessed") != null && !jsonObj.get("bytesProcessed").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("bytesProcessed"));
      }
      // validate the optional field `bytesWritten`
      if (jsonObj.get("bytesWritten") != null && !jsonObj.get("bytesWritten").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("bytesWritten"));
      }
      // validate the optional field `recordsProcessed`
      if (jsonObj.get("recordsProcessed") != null && !jsonObj.get("recordsProcessed").isJsonNull()) {
        Integer.validateJsonElement(jsonObj.get("recordsProcessed"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ExecutionResult.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ExecutionResult' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ExecutionResult> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ExecutionResult.class));

       return (TypeAdapter<T>) new TypeAdapter<ExecutionResult>() {
           @Override
           public void write(JsonWriter out, ExecutionResult value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ExecutionResult read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ExecutionResult given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ExecutionResult
   * @throws IOException if the JSON string is invalid with respect to ExecutionResult
   */
  public static ExecutionResult fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ExecutionResult.class);
  }

  /**
   * Convert an instance of ExecutionResult to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

