/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 *  The OAuth properties required for OAuth type authentication. 
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class OAuthProperties {
  public static final String SERIALIZED_NAME_TOKEN_URL = "tokenUrl";
  @SerializedName(SERIALIZED_NAME_TOKEN_URL)
  @javax.annotation.Nonnull
  private String tokenUrl;

  public static final String SERIALIZED_NAME_AUTH_CODE_URL = "authCodeUrl";
  @SerializedName(SERIALIZED_NAME_AUTH_CODE_URL)
  @javax.annotation.Nonnull
  private String authCodeUrl;

  public static final String SERIALIZED_NAME_O_AUTH_SCOPES = "oAuthScopes";
  @SerializedName(SERIALIZED_NAME_O_AUTH_SCOPES)
  @javax.annotation.Nonnull
  private List oAuthScopes;

  public OAuthProperties() {
  }

  public OAuthProperties tokenUrl(@javax.annotation.Nonnull String tokenUrl) {
    this.tokenUrl = tokenUrl;
    return this;
  }

  /**
   * Get tokenUrl
   * @return tokenUrl
   */
  @javax.annotation.Nonnull
  public String getTokenUrl() {
    return tokenUrl;
  }

  public void setTokenUrl(@javax.annotation.Nonnull String tokenUrl) {
    this.tokenUrl = tokenUrl;
  }


  public OAuthProperties authCodeUrl(@javax.annotation.Nonnull String authCodeUrl) {
    this.authCodeUrl = authCodeUrl;
    return this;
  }

  /**
   * Get authCodeUrl
   * @return authCodeUrl
   */
  @javax.annotation.Nonnull
  public String getAuthCodeUrl() {
    return authCodeUrl;
  }

  public void setAuthCodeUrl(@javax.annotation.Nonnull String authCodeUrl) {
    this.authCodeUrl = authCodeUrl;
  }


  public OAuthProperties oAuthScopes(@javax.annotation.Nonnull List oAuthScopes) {
    this.oAuthScopes = oAuthScopes;
    return this;
  }

  /**
   * Get oAuthScopes
   * @return oAuthScopes
   */
  @javax.annotation.Nonnull
  public List getoAuthScopes() {
    return oAuthScopes;
  }

  public void setoAuthScopes(@javax.annotation.Nonnull List oAuthScopes) {
    this.oAuthScopes = oAuthScopes;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuthProperties oauthProperties = (OAuthProperties) o;
    return Objects.equals(this.tokenUrl, oauthProperties.tokenUrl) &&
        Objects.equals(this.authCodeUrl, oauthProperties.authCodeUrl) &&
        Objects.equals(this.oAuthScopes, oauthProperties.oAuthScopes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenUrl, authCodeUrl, oAuthScopes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuthProperties {\n");
    sb.append("    tokenUrl: ").append(toIndentedString(tokenUrl)).append("\n");
    sb.append("    authCodeUrl: ").append(toIndentedString(authCodeUrl)).append("\n");
    sb.append("    oAuthScopes: ").append(toIndentedString(oAuthScopes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tokenUrl");
    openapiFields.add("authCodeUrl");
    openapiFields.add("oAuthScopes");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("tokenUrl");
    openapiRequiredFields.add("authCodeUrl");
    openapiRequiredFields.add("oAuthScopes");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OAuthProperties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OAuthProperties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OAuthProperties is not found in the empty JSON string", OAuthProperties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OAuthProperties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OAuthProperties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OAuthProperties.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `tokenUrl`
      String.validateJsonElement(jsonObj.get("tokenUrl"));
      // validate the required field `authCodeUrl`
      String.validateJsonElement(jsonObj.get("authCodeUrl"));
      // validate the required field `oAuthScopes`
      List.validateJsonElement(jsonObj.get("oAuthScopes"));
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OAuthProperties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OAuthProperties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OAuthProperties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OAuthProperties.class));

       return (TypeAdapter<T>) new TypeAdapter<OAuthProperties>() {
           @Override
           public void write(JsonWriter out, OAuthProperties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OAuthProperties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OAuthProperties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OAuthProperties
   * @throws IOException if the JSON string is invalid with respect to OAuthProperties
   */
  public static OAuthProperties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OAuthProperties.class);
  }

  /**
   * Convert an instance of OAuthProperties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

