/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.OAuth2CustomPropType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Custom parameter required for OAuth 2.0 authentication.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class OAuth2CustomParameter {
  public static final String SERIALIZED_NAME_KEY = "key";
  @SerializedName(SERIALIZED_NAME_KEY)
  @javax.annotation.Nullable
  private String key;

  public static final String SERIALIZED_NAME_IS_REQUIRED = "isRequired";
  @SerializedName(SERIALIZED_NAME_IS_REQUIRED)
  @javax.annotation.Nullable
  private Boolean isRequired;

  public static final String SERIALIZED_NAME_LABEL = "label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  @javax.annotation.Nullable
  private String label;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_IS_SENSITIVE_FIELD = "isSensitiveField";
  @SerializedName(SERIALIZED_NAME_IS_SENSITIVE_FIELD)
  @javax.annotation.Nullable
  private Boolean isSensitiveField;

  public static final String SERIALIZED_NAME_CONNECTOR_SUPPLIED_VALUES = "connectorSuppliedValues";
  @SerializedName(SERIALIZED_NAME_CONNECTOR_SUPPLIED_VALUES)
  @javax.annotation.Nullable
  private List connectorSuppliedValues;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private OAuth2CustomPropType type;

  public OAuth2CustomParameter() {
  }

  public OAuth2CustomParameter key(@javax.annotation.Nullable String key) {
    this.key = key;
    return this;
  }

  /**
   * Get key
   * @return key
   */
  @javax.annotation.Nullable
  public String getKey() {
    return key;
  }

  public void setKey(@javax.annotation.Nullable String key) {
    this.key = key;
  }


  public OAuth2CustomParameter isRequired(@javax.annotation.Nullable Boolean isRequired) {
    this.isRequired = isRequired;
    return this;
  }

  /**
   * Get isRequired
   * @return isRequired
   */
  @javax.annotation.Nullable
  public Boolean getIsRequired() {
    return isRequired;
  }

  public void setIsRequired(@javax.annotation.Nullable Boolean isRequired) {
    this.isRequired = isRequired;
  }


  public OAuth2CustomParameter label(@javax.annotation.Nullable String label) {
    this.label = label;
    return this;
  }

  /**
   * Get label
   * @return label
   */
  @javax.annotation.Nullable
  public String getLabel() {
    return label;
  }

  public void setLabel(@javax.annotation.Nullable String label) {
    this.label = label;
  }


  public OAuth2CustomParameter description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public OAuth2CustomParameter isSensitiveField(@javax.annotation.Nullable Boolean isSensitiveField) {
    this.isSensitiveField = isSensitiveField;
    return this;
  }

  /**
   * Get isSensitiveField
   * @return isSensitiveField
   */
  @javax.annotation.Nullable
  public Boolean getIsSensitiveField() {
    return isSensitiveField;
  }

  public void setIsSensitiveField(@javax.annotation.Nullable Boolean isSensitiveField) {
    this.isSensitiveField = isSensitiveField;
  }


  public OAuth2CustomParameter connectorSuppliedValues(@javax.annotation.Nullable List connectorSuppliedValues) {
    this.connectorSuppliedValues = connectorSuppliedValues;
    return this;
  }

  /**
   * Get connectorSuppliedValues
   * @return connectorSuppliedValues
   */
  @javax.annotation.Nullable
  public List getConnectorSuppliedValues() {
    return connectorSuppliedValues;
  }

  public void setConnectorSuppliedValues(@javax.annotation.Nullable List connectorSuppliedValues) {
    this.connectorSuppliedValues = connectorSuppliedValues;
  }


  public OAuth2CustomParameter type(@javax.annotation.Nullable OAuth2CustomPropType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public OAuth2CustomPropType getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable OAuth2CustomPropType type) {
    this.type = type;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuth2CustomParameter oauth2CustomParameter = (OAuth2CustomParameter) o;
    return Objects.equals(this.key, oauth2CustomParameter.key) &&
        Objects.equals(this.isRequired, oauth2CustomParameter.isRequired) &&
        Objects.equals(this.label, oauth2CustomParameter.label) &&
        Objects.equals(this.description, oauth2CustomParameter.description) &&
        Objects.equals(this.isSensitiveField, oauth2CustomParameter.isSensitiveField) &&
        Objects.equals(this.connectorSuppliedValues, oauth2CustomParameter.connectorSuppliedValues) &&
        Objects.equals(this.type, oauth2CustomParameter.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, isRequired, label, description, isSensitiveField, connectorSuppliedValues, type);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuth2CustomParameter {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    isRequired: ").append(toIndentedString(isRequired)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isSensitiveField: ").append(toIndentedString(isSensitiveField)).append("\n");
    sb.append("    connectorSuppliedValues: ").append(toIndentedString(connectorSuppliedValues)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("key");
    openapiFields.add("isRequired");
    openapiFields.add("label");
    openapiFields.add("description");
    openapiFields.add("isSensitiveField");
    openapiFields.add("connectorSuppliedValues");
    openapiFields.add("type");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OAuth2CustomParameter
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OAuth2CustomParameter.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OAuth2CustomParameter is not found in the empty JSON string", OAuth2CustomParameter.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OAuth2CustomParameter.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OAuth2CustomParameter` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `key`
      if (jsonObj.get("key") != null && !jsonObj.get("key").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("key"));
      }
      // validate the optional field `isRequired`
      if (jsonObj.get("isRequired") != null && !jsonObj.get("isRequired").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isRequired"));
      }
      // validate the optional field `label`
      if (jsonObj.get("label") != null && !jsonObj.get("label").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("label"));
      }
      // validate the optional field `description`
      if (jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) {
        String.validateJsonElement(jsonObj.get("description"));
      }
      // validate the optional field `isSensitiveField`
      if (jsonObj.get("isSensitiveField") != null && !jsonObj.get("isSensitiveField").isJsonNull()) {
        Boolean.validateJsonElement(jsonObj.get("isSensitiveField"));
      }
      // validate the optional field `connectorSuppliedValues`
      if (jsonObj.get("connectorSuppliedValues") != null && !jsonObj.get("connectorSuppliedValues").isJsonNull()) {
        List.validateJsonElement(jsonObj.get("connectorSuppliedValues"));
      }
      // validate the optional field `type`
      if (jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) {
        OAuth2CustomPropType.validateJsonElement(jsonObj.get("type"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OAuth2CustomParameter.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OAuth2CustomParameter' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OAuth2CustomParameter> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OAuth2CustomParameter.class));

       return (TypeAdapter<T>) new TypeAdapter<OAuth2CustomParameter>() {
           @Override
           public void write(JsonWriter out, OAuth2CustomParameter value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OAuth2CustomParameter read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OAuth2CustomParameter given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OAuth2CustomParameter
   * @throws IOException if the JSON string is invalid with respect to OAuth2CustomParameter
   */
  public static OAuth2CustomParameter fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OAuth2CustomParameter.class);
  }

  /**
   * Convert an instance of OAuth2CustomParameter to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

