/*
 * Amazon Appflow
 * <p>Welcome to the Amazon AppFlow API reference. This guide is for developers who need detailed information about the Amazon AppFlow API operations, data types, and errors. </p> <p>Amazon AppFlow is a fully managed integration service that enables you to securely transfer data between software as a service (SaaS) applications like Salesforce, Marketo, Slack, and ServiceNow, and Amazon Web Services like Amazon S3 and Amazon Redshift. </p> <p>Use the following links to get started on the Amazon AppFlow API:</p> <ul> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Operations.html\">Actions</a>: An alphabetical list of all Amazon AppFlow API operations.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/API_Types.html\">Data types</a>: An alphabetical list of all Amazon AppFlow data types.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonParameters.html\">Common parameters</a>: Parameters that all Query operations can use.</p> </li> <li> <p> <a href=\"https://docs.aws.amazon.com/appflow/1.0/APIReference/CommonErrors.html\">Common errors</a>: Client and server errors that all operations can return.</p> </li> </ul> <p>If you're new to Amazon AppFlow, we recommend that you review the <a href=\"https://docs.aws.amazon.com/appflow/latest/userguide/what-is-appflow.html\">Amazon AppFlow User Guide</a>.</p> <p>Amazon AppFlow API users can use vendor-specific mechanisms for OAuth, and include applicable OAuth attributes (such as <code>auth-code</code> and <code>redirecturi</code>) with the connector-specific <code>ConnectorProfileProperties</code> when creating a new connector profile using Amazon AppFlow API operations. For example, Salesforce users can refer to the <a href=\"https://help.salesforce.com/articleView?id=remoteaccess_authenticate.htm\"> <i>Authorize Apps with OAuth</i> </a> documentation.</p>
 *
 * The version of the OpenAPI document: 2020-08-23
 * Contact: mike.ralphson@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.Map;
import org.openapitools.client.model.OAuth2GrantType;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * The OAuth 2.0 properties required for OAuth 2.0 authentication.
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-08-25T13:42:27.578242+05:30[Asia/Kolkata]", comments = "Generator version: 7.10.0")
public class OAuth2Properties {
  public static final String SERIALIZED_NAME_TOKEN_URL = "tokenUrl";
  @SerializedName(SERIALIZED_NAME_TOKEN_URL)
  @javax.annotation.Nonnull
  private String tokenUrl;

  public static final String SERIALIZED_NAME_O_AUTH2_GRANT_TYPE = "oAuth2GrantType";
  @SerializedName(SERIALIZED_NAME_O_AUTH2_GRANT_TYPE)
  @javax.annotation.Nonnull
  private OAuth2GrantType oAuth2GrantType;

  public static final String SERIALIZED_NAME_TOKEN_URL_CUSTOM_PROPERTIES = "tokenUrlCustomProperties";
  @SerializedName(SERIALIZED_NAME_TOKEN_URL_CUSTOM_PROPERTIES)
  @javax.annotation.Nullable
  private Map tokenUrlCustomProperties;

  public OAuth2Properties() {
  }

  public OAuth2Properties tokenUrl(@javax.annotation.Nonnull String tokenUrl) {
    this.tokenUrl = tokenUrl;
    return this;
  }

  /**
   * Get tokenUrl
   * @return tokenUrl
   */
  @javax.annotation.Nonnull
  public String getTokenUrl() {
    return tokenUrl;
  }

  public void setTokenUrl(@javax.annotation.Nonnull String tokenUrl) {
    this.tokenUrl = tokenUrl;
  }


  public OAuth2Properties oAuth2GrantType(@javax.annotation.Nonnull OAuth2GrantType oAuth2GrantType) {
    this.oAuth2GrantType = oAuth2GrantType;
    return this;
  }

  /**
   * Get oAuth2GrantType
   * @return oAuth2GrantType
   */
  @javax.annotation.Nonnull
  public OAuth2GrantType getoAuth2GrantType() {
    return oAuth2GrantType;
  }

  public void setoAuth2GrantType(@javax.annotation.Nonnull OAuth2GrantType oAuth2GrantType) {
    this.oAuth2GrantType = oAuth2GrantType;
  }


  public OAuth2Properties tokenUrlCustomProperties(@javax.annotation.Nullable Map tokenUrlCustomProperties) {
    this.tokenUrlCustomProperties = tokenUrlCustomProperties;
    return this;
  }

  /**
   * Get tokenUrlCustomProperties
   * @return tokenUrlCustomProperties
   */
  @javax.annotation.Nullable
  public Map getTokenUrlCustomProperties() {
    return tokenUrlCustomProperties;
  }

  public void setTokenUrlCustomProperties(@javax.annotation.Nullable Map tokenUrlCustomProperties) {
    this.tokenUrlCustomProperties = tokenUrlCustomProperties;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OAuth2Properties oauth2Properties = (OAuth2Properties) o;
    return Objects.equals(this.tokenUrl, oauth2Properties.tokenUrl) &&
        Objects.equals(this.oAuth2GrantType, oauth2Properties.oAuth2GrantType) &&
        Objects.equals(this.tokenUrlCustomProperties, oauth2Properties.tokenUrlCustomProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tokenUrl, oAuth2GrantType, tokenUrlCustomProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OAuth2Properties {\n");
    sb.append("    tokenUrl: ").append(toIndentedString(tokenUrl)).append("\n");
    sb.append("    oAuth2GrantType: ").append(toIndentedString(oAuth2GrantType)).append("\n");
    sb.append("    tokenUrlCustomProperties: ").append(toIndentedString(tokenUrlCustomProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tokenUrl");
    openapiFields.add("oAuth2GrantType");
    openapiFields.add("tokenUrlCustomProperties");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("tokenUrl");
    openapiRequiredFields.add("oAuth2GrantType");
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to OAuth2Properties
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!OAuth2Properties.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in OAuth2Properties is not found in the empty JSON string", OAuth2Properties.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!OAuth2Properties.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `OAuth2Properties` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : OAuth2Properties.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the required field `tokenUrl`
      String.validateJsonElement(jsonObj.get("tokenUrl"));
      // validate the required field `oAuth2GrantType`
      OAuth2GrantType.validateJsonElement(jsonObj.get("oAuth2GrantType"));
      // validate the optional field `tokenUrlCustomProperties`
      if (jsonObj.get("tokenUrlCustomProperties") != null && !jsonObj.get("tokenUrlCustomProperties").isJsonNull()) {
        Map.validateJsonElement(jsonObj.get("tokenUrlCustomProperties"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!OAuth2Properties.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'OAuth2Properties' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<OAuth2Properties> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(OAuth2Properties.class));

       return (TypeAdapter<T>) new TypeAdapter<OAuth2Properties>() {
           @Override
           public void write(JsonWriter out, OAuth2Properties value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public OAuth2Properties read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of OAuth2Properties given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of OAuth2Properties
   * @throws IOException if the JSON string is invalid with respect to OAuth2Properties
   */
  public static OAuth2Properties fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, OAuth2Properties.class);
  }

  /**
   * Convert an instance of OAuth2Properties to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

